version: "3"

services:
  app:
    build: ./app
    volumes:
      - ./app:/var/www/html:z
    depends_on:
      - mysql
    ports:
      - "80:80"
    env_file:
      - .env

  mysql:
    image: mysql:5.7
    volumes:
      - ./db_structure.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=default